name: Release Debug
on:
  push:
    branches:
      - develop
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: borales/actions-yarn@master
        with:
          cmd: install
      - name: Release
        uses: borales/actions-yarn@master
        with:
          cmd: build
      - name: Zip&Upload
        uses: actions/upload-artifact@v2
        with:
          name: admin
          path: build/
