name: CICD
on:
  pull_request:
    branches:
      - '**'
jobs:
  test:
    name: testcases runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        uses: borales/actions-yarn@master
        with:
          cmd: install
      - name: CICD
        uses: borales/actions-yarn@master
        with:
          cmd: test
      